version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reliabill
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  relia-bill:
    build: .
    container_name: relia-bill-app
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/reliabill
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

  liquibase:
    image: maven:3.8
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: mvn liquibase:update
    depends_on:
      - mariadb

volumes:
  mariadb_data:
